add experiment tracking integration to text, image classification & LLM finetuning
huggingface/autotrain-advanced pull request #301
Opened 2023-10-16 15:36 UTC by rishiraj

Worked with @soumik12345 from WandB team to successfully integrate WandB with LLM Finetuning, text & image classification. Tests are passing. Here is a notebook I used to test: https://colab.research.google.com/drive/1m0KZzcCuKRn3Rkff32XTvdIfD45hK2Va?usp=sharing

2023-10-16 15:52 UTC, rishiraj commented
Worked with @soumik12345 from WandB team to successfully integrate WandB with LLM Finetuning, text & image classification. Tests are passing. Here is a notebook I used to test: https://colab.research.google.com/drive/1m0KZzcCuKRn3Rkff32XTvdIfD45hK2Va?usp=sharing

2023-10-17 10:43 UTC, abhishekkrthakur requested changes
Thanks for the PR. Eventually, multiple logging should be supported. Currently, we already have tensorboard. In order to get this PR merged, we need to change how the API works. The CLI should have a `--log` argument which can take inputs like `tensorboard` and `wandb`. `--log wandb` should log to wandb and so on. if nothing is provided, no logging. please let me know if the requirements are unclear

2023-10-17 13:44 UTC, rishiraj commented
> Thanks for the PR. Eventually, multiple logging should be supported. Currently, we already have tensorboard. In order to get this PR merged, we need to change how the API works. The CLI should have a `--log` argument which can take inputs like `tensorboard` and `wandb`. `--log wandb` should log to wandb and so on. if nothing is provided, no logging. please let me know if the requirements are unclear

The requirements are clear. I am working to make the required changes.

2023-10-18 00:58 UTC, rishiraj commented
> Thanks for the PR. Eventually, multiple logging should be supported. Currently, we already have tensorboard. In order to get this PR merged, we need to change how the API works. The CLI should have a `--log` argument which can take inputs like `tensorboard` and `wandb`. `--log wandb` should log to wandb and so on. if nothing is provided, no logging. please let me know if the requirements are unclear

@abhishekkrthakur Made the changes you requested and successfully integrated all experiment trackers like "azure_ml", "clearml", "codecarbon", "comet_ml", "dagshub", "flyte", "mlflow", "neptune", "tensorboard", and "wandb" with LLM Finetuning, text & image classification via the `--log` argument. Tests are passing. Here is a notebook I used to test: https://colab.research.google.com/drive/1m0KZzcCuKRn3Rkff32XTvdIfD45hK2Va?usp=sharing

2023-10-22 06:12 UTC, abhishekkrthakur requested changes

2023-10-22 06:12 UTC, abhishekkrthakur commented on src/autotrain/trainers/lm_trainer.py
remove changes from this file please. its deprecated and will be removed soon.

2023-10-22 06:12 UTC, abhishekkrthakur commented on src/autotrain/trainers/text_classification.py
remove changes from this file please. its deprecated and will be removed soon.

2023-10-22 06:19 UTC, abhishekkrthakur commented
Please also run: `make style && make quality`

2023-10-22 06:22 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/autotrain/pr_301). All of your documentation changes will be reflected on that endpoint.

2023-10-22 06:49 UTC, rishiraj commented on src/autotrain/trainers/lm_trainer.py
removed changes from this file and tested ok using the colab link.

2023-10-22 06:49 UTC, rishiraj commented on src/autotrain/trainers/text_classification.py
removed changes from this file and tested ok using the colab link.

2023-10-22 06:57 UTC, merged

2023-10-22 06:58 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/autotrain/pr_301). All of your documentation changes will be reflected on that endpoint.