Add distilabel gen
huggingface/autotrain-advanced pull request #819
Opened 2024-12-04 12:33 UTC by sdiazlor

- I added distilabel to run locally using LlamaCpp and outlines.
- distilabel typically works with pipelines, but in this case, I use the task isolated as after some testing, pipelines were overcomplicating the code.

As it's using LlamaCpp, the user will need to indicate the path to the gguf file, as with csv when training, but I wasn't sure where I should update those parameters.

2024-12-04 12:36 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/autotrain/pr_819). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-12-04 13:02 UTC, abhishekkrthakur requested changes

2024-12-04 14:44 UTC, sdiazlor commented on requirements.txt
> +outlines==0.0.46
Yes, to run, it needs some extra dependencies: https://distilabel.argilla.io/latest/sections/getting_started/installation/#extras

2024-12-04 14:47 UTC, abhishekkrthakur commented on requirements.txt
> +outlines==0.0.46
sorry, i meant that its missing from requirements, no?

2024-12-04 15:34 UTC, sdiazlor commented on requirements.txt
> +outlines==0.0.46
My bad, yes!

2024-12-09 13:23 UTC, abhishekkrthakur approved these changes

2024-12-09 13:23 UTC, merged